//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace superduperfinal.thesis
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbconEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbconEntities object using the connection string found in the 'dbconEntities' section of the application configuration file.
        /// </summary>
        public dbconEntities() : base("name=dbconEntities", "dbconEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbconEntities object.
        /// </summary>
        public dbconEntities(string connectionString) : base(connectionString, "dbconEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbconEntities object.
        /// </summary>
        public dbconEntities(EntityConnection connection) : base(connection, "dbconEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<logs> logs
        {
            get
            {
                if ((_logs == null))
                {
                    _logs = base.CreateObjectSet<logs>("logs");
                }
                return _logs;
            }
        }
        private ObjectSet<logs> _logs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_people> tbl_people
        {
            get
            {
                if ((_tbl_people == null))
                {
                    _tbl_people = base.CreateObjectSet<tbl_people>("tbl_people");
                }
                return _tbl_people;
            }
        }
        private ObjectSet<tbl_people> _tbl_people;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the logs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTologs(logs logs)
        {
            base.AddObject("logs", logs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_people EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_people(tbl_people tbl_people)
        {
            base.AddObject("tbl_people", tbl_people);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbconModel", Name="logs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class logs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new logs object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static logs Createlogs(global::System.Int32 id)
        {
            logs logs = new logs();
            logs.ID = id;
            return logs;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.String _Role;
        partial void OnRoleChanging(global::System.String value);
        partial void OnRoleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Date_time
        {
            get
            {
                return _Date_time;
            }
            set
            {
                OnDate_timeChanging(value);
                ReportPropertyChanging("Date_time");
                _Date_time = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Date_time");
                OnDate_timeChanged();
            }
        }
        private global::System.String _Date_time;
        partial void OnDate_timeChanging(global::System.String value);
        partial void OnDate_timeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Activity
        {
            get
            {
                return _Activity;
            }
            set
            {
                OnActivityChanging(value);
                ReportPropertyChanging("Activity");
                _Activity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Activity");
                OnActivityChanged();
            }
        }
        private global::System.String _Activity;
        partial void OnActivityChanging(global::System.String value);
        partial void OnActivityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbconModel", Name="tbl_people")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_people : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_people object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static tbl_people Createtbl_people(global::System.Int32 id)
        {
            tbl_people tbl_people = new tbl_people();
            tbl_people.ID = id;
            return tbl_people;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nick_Name
        {
            get
            {
                return _Nick_Name;
            }
            set
            {
                OnNick_NameChanging(value);
                ReportPropertyChanging("Nick_Name");
                _Nick_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nick_Name");
                OnNick_NameChanged();
            }
        }
        private global::System.String _Nick_Name;
        partial void OnNick_NameChanging(global::System.String value);
        partial void OnNick_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String First_Name
        {
            get
            {
                return _First_Name;
            }
            set
            {
                OnFirst_NameChanging(value);
                ReportPropertyChanging("First_Name");
                _First_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("First_Name");
                OnFirst_NameChanged();
            }
        }
        private global::System.String _First_Name;
        partial void OnFirst_NameChanging(global::System.String value);
        partial void OnFirst_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Middle_Name
        {
            get
            {
                return _Middle_Name;
            }
            set
            {
                OnMiddle_NameChanging(value);
                ReportPropertyChanging("Middle_Name");
                _Middle_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Middle_Name");
                OnMiddle_NameChanged();
            }
        }
        private global::System.String _Middle_Name;
        partial void OnMiddle_NameChanging(global::System.String value);
        partial void OnMiddle_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Last_Name
        {
            get
            {
                return _Last_Name;
            }
            set
            {
                OnLast_NameChanging(value);
                ReportPropertyChanging("Last_Name");
                _Last_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Last_Name");
                OnLast_NameChanged();
            }
        }
        private global::System.String _Last_Name;
        partial void OnLast_NameChanging(global::System.String value);
        partial void OnLast_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Street_Name
        {
            get
            {
                return _Street_Name;
            }
            set
            {
                OnStreet_NameChanging(value);
                ReportPropertyChanging("Street_Name");
                _Street_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Street_Name");
                OnStreet_NameChanged();
            }
        }
        private global::System.String _Street_Name;
        partial void OnStreet_NameChanging(global::System.String value);
        partial void OnStreet_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String House__
        {
            get
            {
                return _House__;
            }
            set
            {
                OnHouse__Changing(value);
                ReportPropertyChanging("House__");
                _House__ = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("House__");
                OnHouse__Changed();
            }
        }
        private global::System.String _House__;
        partial void OnHouse__Changing(global::System.String value);
        partial void OnHouse__Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private global::System.String _Birthday;
        partial void OnBirthdayChanging(global::System.String value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Birthplace
        {
            get
            {
                return _Birthplace;
            }
            set
            {
                OnBirthplaceChanging(value);
                ReportPropertyChanging("Birthplace");
                _Birthplace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Birthplace");
                OnBirthplaceChanged();
            }
        }
        private global::System.String _Birthplace;
        partial void OnBirthplaceChanging(global::System.String value);
        partial void OnBirthplaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Occupation
        {
            get
            {
                return _Occupation;
            }
            set
            {
                OnOccupationChanging(value);
                ReportPropertyChanging("Occupation");
                _Occupation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Occupation");
                OnOccupationChanged();
            }
        }
        private global::System.String _Occupation;
        partial void OnOccupationChanging(global::System.String value);
        partial void OnOccupationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Records
        {
            get
            {
                return _Records;
            }
            set
            {
                OnRecordsChanging(value);
                ReportPropertyChanging("Records");
                _Records = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Records");
                OnRecordsChanged();
            }
        }
        private global::System.String _Records;
        partial void OnRecordsChanging(global::System.String value);
        partial void OnRecordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.String _Age;
        partial void OnAgeChanging(global::System.String value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Stats
        {
            get
            {
                return _Stats;
            }
            set
            {
                OnStatsChanging(value);
                ReportPropertyChanging("Stats");
                _Stats = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Stats");
                OnStatsChanged();
            }
        }
        private global::System.String _Stats;
        partial void OnStatsChanging(global::System.String value);
        partial void OnStatsChanged();

        #endregion
    
    }

    #endregion
    
}
